apiVersion: v1
kind: Service
metadata:
  name: {{ include "k6s.fullname" . }}
  labels:
    {{- include "k6s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "k6s.selectorLabels" . | nindent 4 }}
