image:
  repository: k8s-ctrl
  tag: "latest"
  pullPolicy: Always

replicaCount: 1

env:
  LOG_LEVEL: info

args:
  - --in-cluster

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 45
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 40
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

volumeMounts: []
volumes: []

service:
  name: http
  type: ClusterIP
  port: 80
  protocol: TCP
  targetPort: 8080

serviceAccount:
  create: true
  name: ""
  annotations: {}
