clusters:
  - name: "minikube"
    kubeconfig: "/Users/rpovoroznyk/.kube/config"
    context: "minikube"
    server: ""
    namespace: "default"
    enabled: true
    primary: true
default_namespace: "default"
connection_timeout: "30s"
max_concurrent_connections: 10
