name: CI

on:
  push:
    branches: [ "master", "feature/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set version
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            APP_VERSION=${VERSION}
            DOCKER_TAG=${VERSION}
          else
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
            VERSION="0.1.0+${GITHUB_SHA}"
            APP_VERSION=${GITHUB_SHA}
            DOCKER_TAG="0.1.0-${SHORT_SHA}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "docker_tag=$DOCKER_TAG" >> $GITHUB_OUTPUT

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Generate code coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.docker_tag }} --build-arg VERSION=${{ steps.vars.outputs.version }} .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.18.0
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.docker_tag }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.docker_tag }}
